// <auto-generated />
using System;
using Blog.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Blog.DbMigrator.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20210328144022_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Blog.Domain.Shared.Article.ArticleTag", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ArticlePOID")
                        .HasColumnType("text")
                        .HasColumnName("article_poid");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Name")
                        .HasName("pk_article_tags");

                    b.HasIndex("ArticlePOID")
                        .HasDatabaseName("ix_article_tags_article_poid");

                    b.ToTable("article_tags");
                });

            modelBuilder.Entity("Blog.Infrastructure.Models.ArticlePO", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("CommentCounts")
                        .HasColumnType("integer")
                        .HasColumnName("comment_counts");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("create_date");

                    b.Property<int>("ReadCounts")
                        .HasColumnType("integer")
                        .HasColumnName("read_counts");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.Property<string>("SubTitle")
                        .HasColumnType("text")
                        .HasColumnName("sub_title");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("update_date");

                    b.HasKey("ID")
                        .HasName("pk_articles");

                    b.ToTable("articles");
                });

            modelBuilder.Entity("Blog.Domain.Shared.Article.ArticleTag", b =>
                {
                    b.HasOne("Blog.Infrastructure.Models.ArticlePO", null)
                        .WithMany("Tags")
                        .HasForeignKey("ArticlePOID")
                        .HasConstraintName("fk_article_tags_articles_article_poid");
                });

            modelBuilder.Entity("Blog.Infrastructure.Models.ArticlePO", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
